language: node_js
node_js:
  - node

stages:
  - compile
  - test
  - name: deploy
    if: branch = master AND type = push AND fork = false

jobs:
  include:
    - stage: test
      name: "Test GAS"
      script:
        - echo $LOCAL_CLASPRC_JSON > .clasprc.json
        - echo $GLOBAL_CLASPRC_JSON > ~/.clasprc.json
        - echo $CLASP_JSON > .clasp.json
        - npm run test
    - stage: deploy
      name: "Deploy to GCP"
      script: 
        - echo $LOCAL_CLASPRC_JSON > .clasprc.json
        - echo $GLOBAL_CLASPRC_JSON > ~/.clasprc.json
        - echo $CLASP_JSON > .clasp.json
        - npm run push
        
