language: node_js
node_js:
  - node

stages:
  - compile
  - test
  - name: deploy
    if: type = push AND fork = false
    branch:
      only:
        master

jobs:
  include:
    - stage: deploy
      name: "Deploy to GCP"
      script: 
        - echo $CLASPRC_JSON > ~/.clasprc.json
        - echo $CLASP_JSON > .clasp.json
        - npm run push
        
