language: node_js
node_js:
  - node

stages:
  - compile
  - test
  - deploy

jobs:
  include:
    - stage: deploy
      name: "Deploy to GCP"
      script: 
        - echo $CLASPRC_JSON > ~/.clasprc.json
        - echo $CLASP_JSON > .clasp.json
        - npm run push
        
