language: node_js
node_js:
- 13.13.0

before_script: npm install

script:
  - echo $CLASPRC_JSON > ~/.clasprc.json
  - echo $CLASP_JSON > .clasp.json
  - cd ~
  - ls -a
  - cd -
  - cat ~/.clasprc.json
  - npm run login