box: node

build:
  steps:
    - npm-install

    - script:
        name: init .clasprc.json .clasp.json
        code: |
          echo $CLASPRC_JSON > ~/.clasprc.json
          echo $CLASP_JSON > .clasp.json
    - script:
        name: push
        code: |
          npm run deploy
